name: Run QVerse.py

on:
  schedule:
    - cron: '*/30 * * * *'  # Set the schedule here (every 30 minutes in this example)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: create virtual environment
        run: python -m venv myenv

      - name: activate virtual environment
        run: source myenv/bin/activate

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Dependencies
        run: |
          pip install Pillow requests instagrapi
      

      - name: run QVerse.py
        run: python QVerse.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main