name: Run QVerse.py with Random Delay

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  run-random-time:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Random Time Delay
        id: random_delay
        run: |
          hour=$(shuf -i 0-23 -n 1)   # Random hour (0-23)
          minute=$(shuf -i 0-59 -n 1) # Random minute (0-59)
          seconds_until_run=$(( (hour * 3600) + (minute * 60) ))
          echo "Waiting for $seconds_until_run seconds until execution."
          echo "SECONDS_UNTIL_RUN=$seconds_until_run" >> $GITHUB_ENV

      - name: Sleep Until Random Time
        run: sleep $SECONDS_UNTIL_RUN

      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libjpeg-dev zlib1g-dev fontconfig

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow

      - name: Run Python script
        run: python QVerse.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
