name: Run QVerse.py Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC

jobs:
  run-fixed-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libjpeg-dev zlib1g-dev fontconfig libfreetype6-dev libharfbuzz-dev

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pillow

      - name: Run Python script
        run: python QVerse.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
