name: Run QVerse.py with Random Time

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Default placeholder schedule (runs daily)

jobs:
  set-random-time:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Random Time
        id: random_time
        run: |
          hour=$(shuf -i 0-23 -n 1)   # Random hour between 0-23
          minute=$(shuf -i 0-59 -n 1) # Random minute between 0-59
          echo "hour=${hour}" >> $GITHUB_ENV
          echo "minute=${minute}" >> $GITHUB_ENV
          echo "Generated Random Time: ${hour}:${minute}"

  build:
    runs-on: ubuntu-latest
    needs: set-random-time
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow

      - name: Run Python script
        run: python QVerse.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

  reschedule:
    runs-on: ubuntu-latest
    needs: [set-random-time, build]
    steps:
      - name: Update Workflow Schedule
        run: |
          echo "Updating the workflow to run daily at ${hour}:${minute}."
        # This step would require committing the updated workflow file if automation is supported.
