name: run QVerse.py

on:
  schedule:
    - cron: '*/30 * * * *'  # Set the schedule here (every 30 minutes in this example)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Specify your desired OS platforms

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version here

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Pillow  # Add this line to install the Pillow library

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
