name: Run QVerse.py

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs the workflow every day at midnight (00:00)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow  

      - name: Execute QVerse.py
        run: python QVerse.py
